### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGNAL'

### ISSUE THREAD

**Issue by puruzio** [7Million/Superset-tutorial#5]
Thanks for the great tutorial.  I just installed Superset, and am now trying to build my first query. When I try a select query from the "example" database, it failed. In fact, queries all fail in SQL Lab regardless of which table I try to read from. I also was able to connect to my SQL Server database and see the tables in it, but a simple select query would fail. (ie. '{e}' is the only thing showing up in the output pane with no explanation on why it failed.).  Every time the query failed, I noticed  this console message. 

AttributeError: module 'signal' has no attribute 'SIGNAL'

I understand this module doesn't work on Windows so I am hoping you figured out a workaround?

FYI. I'm on Windows Server 2012R2. Thank you in advance.

**Comment by puruzio** [comment]
Solved. Thanks.

**Comment by 7Million** [comment]
That's great, I'm sorry had not managed to respond in time
